# Generated by Django 5.0.7 on 2024-07-16 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_like_or_dislikelesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_or_DislikeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.videos')),
            ],
        ),
        migrations.DeleteModel(
            name='Like_or_DislikeLesson',
        ),
    ]
