# Generated by Django 5.0.7 on 2024-07-16 09:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_like_or_dislikevideo_delete_like_or_dislikelesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_or_dislikevideo',
            name='video_model',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(default=1, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'AVI', 'WMV', 'jpg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like_or_dislikevideo',
            name='lesson_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_app.lesson'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
